#!/usr/bin/python

# See file COPYING distributed with dpf for copyright and license.

import wsgiref.simple_server
import dpf.data
import dpf.data.handlers

app = dpf.data.Application('/Users/ch/Desktop/umms/dpf/tmp/data', 
                           [dpf.data.handlers.JSONHandler, 
                            dpf.data.handlers.CSVHandler])

httpd = wsgiref.simple_server.make_server('localhost', 8080, app)
print 'ready to serve on 8080'
httpd.serve_forever()

# eof
